apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: argocd-test-prod
nameSuffix: -prod

commonLabels:
  foo: bar

patchesStrategicMerge:
- deployment_replicas.yaml
- deployment_env.yaml
